### ISSUE TITLE
Integrate IMDB result to iTune API "Search"

### ISSUE THREAD

**Issue by NasGenius** [NasGenius/moviejamz#7]
be able to take the search result from IMDB to search iTunes to retrieve the soundtrack

**Comment by ryanwantspizza** [comment]
I got the first part of this done. Am able to pull the basic album info from itunes using the information returned from imdb. need to do a second call to itunes to then get the complete tracklist for the album.

**Comment by ryanwantspizza** [comment]
Able to log the track list in the console. Just need to test with different movies and this will be done.
